source_dir=/mnt/F/mess/hrady
target_dir=/mnt/F/mess/gallery
target_image_resolution_pct=25
target_preview_resolution_pct=6.25
target_preview_dir_name=preview
files_to_process_mask=*.jpg, *.png
metadata_file_mask=_index.txt
additional_file_mask=note.txt
excluded_subdirectories_mask=x
metadata_ID_to_image_mapping=DSC_<ID>.jpg
no_comments_files_mask=_map*.*,_cedule*.*
gallery_JSON_name=index.json
root_JSON_name=root.json
check_only=true